<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BLR2T2WSF035" name="transaction.CustomFilter" tests="1" failures="1" timestamp="30 Oct 2018 11:33:00 GMT" time="22.714" errors="0">
  <testcase name="verify_CustomFilter" time="22.714" classname="transaction.CustomFilter">
    <failure type="java.lang.AssertionError" message="Following Patient Account Number mismatch, [20181029-109, 20181029-110, 20181029-111, 20181029-114, 20181029-112, 20181029-113, 20181029-107, 20181029-106]">
      <![CDATA[java.lang.AssertionError: Following Patient Account Number mismatch, [20181029-109, 20181029-110, 20181029-111, 20181029-114, 20181029-112, 20181029-113, 20181029-107, 20181029-106]
	at org.testng.Assert.fail(Assert.java:94)
	at pageObjectRepository.transaction.AnalystInbox.verify_CustomFilter(AnalystInbox.java:1359)
	at transaction.CustomFilter.verify_CustomFilter(CustomFilter.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_CustomFilter -->
</testsuite> <!-- transaction.CustomFilter -->
